# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_coef <- function(Y, X) {
    .Call('_scPoissonGamma_initialize_coef', PACKAGE = 'scPoissonGamma', Y, X)
}

initialize_mu_alpha <- function(Y, X_beta) {
    .Call('_scPoissonGamma_initialize_mu_alpha', PACKAGE = 'scPoissonGamma', Y, X_beta)
}

initialize_mu_alpha_with_group <- function(Y, X_beta, group) {
    .Call('_scPoissonGamma_initialize_mu_alpha_with_group', PACKAGE = 'scPoissonGamma', Y, X_beta, group)
}

initialize_coef_multiple_beta <- function(Y, X) {
    .Call('_scPoissonGamma_initialize_coef_multiple_beta', PACKAGE = 'scPoissonGamma', Y, X)
}

initialize_mu_alpha_multiple_beta <- function(Y, X, betas, Z) {
    .Call('_scPoissonGamma_initialize_mu_alpha_multiple_beta', PACKAGE = 'scPoissonGamma', Y, X, betas, Z)
}

initialize_mu_alpha_multiple_beta_nowith_alpha <- function(Y, X, Z) {
    .Call('_scPoissonGamma_initialize_mu_alpha_multiple_beta_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z)
}

initialize_mu_alpha_with_group_multiple_beta <- function(Y, X, betas, Z, group) {
    .Call('_scPoissonGamma_initialize_mu_alpha_with_group_multiple_beta', PACKAGE = 'scPoissonGamma', Y, X, betas, Z, group)
}

initialize_mu_alpha_with_group_multiple_beta_nowith_alpha <- function(Y, X, Z, group) {
    .Call('_scPoissonGamma_initialize_mu_alpha_with_group_multiple_beta_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, group)
}

gradient_beta_psi <- function(Y, X, beta, psi, n) {
    .Call('_scPoissonGamma_gradient_beta_psi', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, n)
}

log_factorial <- function(Y) {
    .Call('_scPoissonGamma_log_factorial', PACKAGE = 'scPoissonGamma', Y)
}

log_factorial_calculated <- function(N) {
    .Call('_scPoissonGamma_log_factorial_calculated', PACKAGE = 'scPoissonGamma', N)
}

LogLikelihood_beta_psi <- function(Y, X, beta, psi, n, sum_log_factorial_Y) {
    .Call('_scPoissonGamma_LogLikelihood_beta_psi', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, n, sum_log_factorial_Y)
}

select_stepsize_for_beta <- function(Y, X, gra_beta, ll, beta, psi, n, gamma, sum_log_factorial_Y, down) {
    .Call('_scPoissonGamma_select_stepsize_for_beta', PACKAGE = 'scPoissonGamma', Y, X, gra_beta, ll, beta, psi, n, gamma, sum_log_factorial_Y, down)
}

select_stepsize_for_psi <- function(Y, X, gra_psi, ll, beta, psi, n, gamma, sum_log_factorial_Y, down) {
    .Call('_scPoissonGamma_select_stepsize_for_psi', PACKAGE = 'scPoissonGamma', Y, X, gra_psi, ll, beta, psi, n, gamma, sum_log_factorial_Y, down)
}

gradient_descent_beta_psi <- function(Y, X, beta, psi, gamma, steps, sum_log_factorial_Y, down) {
    .Call('_scPoissonGamma_gradient_descent_beta_psi', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, gamma, steps, sum_log_factorial_Y, down)
}

gradient_psi <- function(Y, psi, n) {
    .Call('_scPoissonGamma_gradient_psi', PACKAGE = 'scPoissonGamma', Y, psi, n)
}

LogLikelihood_psi <- function(Y, psi, n, sum_log_factorial_Y) {
    .Call('_scPoissonGamma_LogLikelihood_psi', PACKAGE = 'scPoissonGamma', Y, psi, n, sum_log_factorial_Y)
}

select_stepsize_psi_alt <- function(Y, gra_psi, ll, psi, n, gamma, sum_log_factorial_Y, down) {
    .Call('_scPoissonGamma_select_stepsize_psi_alt', PACKAGE = 'scPoissonGamma', Y, gra_psi, ll, psi, n, gamma, sum_log_factorial_Y, down)
}

gradient_descent_alt <- function(Y, psi, gamma, steps, sum_log_factorial_Y, down) {
    .Call('_scPoissonGamma_gradient_descent_alt', PACKAGE = 'scPoissonGamma', Y, psi, gamma, steps, sum_log_factorial_Y, down)
}

PoissionGamma <- function(Y, X, beta, psi, gamma, steps, down) {
    .Call('_scPoissonGamma_PoissionGamma', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, gamma, steps, down)
}

gradient_all <- function(Y, X, beta, psi, mu1, mu2, alpha, posterior, n) {
    .Call('_scPoissonGamma_gradient_all', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, mu1, mu2, alpha, posterior, n)
}

gradient_all_cov <- function(Y, X, beta, psi, mu1, mu2, alpha, posterior, n) {
    .Call('_scPoissonGamma_gradient_all_cov', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, mu1, mu2, alpha, posterior, n)
}

Expected_logLikelihood <- function(Y, X, beta, psi, mu1, mu2, alpha, posterior, n, log_factorial_Y) {
    .Call('_scPoissonGamma_Expected_logLikelihood', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, mu1, mu2, alpha, posterior, n, log_factorial_Y)
}

LogLikelihood_single <- function(Y_i, X_i, beta, psi, mu2, log_factorial_Y_i) {
    .Call('_scPoissonGamma_LogLikelihood_single', PACKAGE = 'scPoissonGamma', Y_i, X_i, beta, psi, mu2, log_factorial_Y_i)
}

Posterior_prob <- function(Y_i, X_i, beta, psi, mu1, mu2, alpha, log_factorial_Y_i) {
    .Call('_scPoissonGamma_Posterior_prob', PACKAGE = 'scPoissonGamma', Y_i, X_i, beta, psi, mu1, mu2, alpha, log_factorial_Y_i)
}

PoissonMix_stepsize_for_beta <- function(Y, X, gra_beta, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_beta', PACKAGE = 'scPoissonGamma', Y, X, gra_beta, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_for_psi <- function(Y, X, gra_psi, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_psi', PACKAGE = 'scPoissonGamma', Y, X, gra_psi, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_for_mu1 <- function(Y, X, gra_mu1, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_mu1', PACKAGE = 'scPoissonGamma', Y, X, gra_mu1, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_for_mu2 <- function(Y, X, gra_mu2, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_mu2', PACKAGE = 'scPoissonGamma', Y, X, gra_mu2, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_for_alpha <- function(Y, X, gra_alpha, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_alpha', PACKAGE = 'scPoissonGamma', Y, X, gra_alpha, ll, beta, psi, mu1, mu2, alpha, posterior, n, gamma, down, log_factorial_Y)
}

gradient_descent_PoissonGamma <- function(Y, X, beta, psi, mu1, mu2, alpha, posterior, n, gamma, steps, down, log_factorial_Y) {
    .Call('_scPoissonGamma_gradient_descent_PoissonGamma', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, mu1, mu2, alpha, posterior, n, gamma, steps, down, log_factorial_Y)
}

gradient_descent_PoissonGamma_alt <- function(Y, X, psi, mu1, mu2, posterior, n, gamma, steps, down, log_factorial_Y) {
    .Call('_scPoissonGamma_gradient_descent_PoissonGamma_alt', PACKAGE = 'scPoissonGamma', Y, X, psi, mu1, mu2, posterior, n, gamma, steps, down, log_factorial_Y)
}

Fisher_information <- function(Y, X, beta, psi, mu1, mu2, alpha, posterior, n) {
    .Call('_scPoissonGamma_Fisher_information', PACKAGE = 'scPoissonGamma', Y, X, beta, psi, mu1, mu2, alpha, posterior, n)
}

EM_PoissonGamma <- function(Y, X, Y_ind_zero, beta, psi, mu1, mu2, alpha, posterior, gamma, steps, EM_steps, n, n_1, down, log_factorial_Y, ReportAll) {
    .Call('_scPoissonGamma_EM_PoissonGamma', PACKAGE = 'scPoissonGamma', Y, X, Y_ind_zero, beta, psi, mu1, mu2, alpha, posterior, gamma, steps, EM_steps, n, n_1, down, log_factorial_Y, ReportAll)
}

EM_PoissonGamma_alt <- function(Y, X, Y_ind_zero, psi, mu1, mu2, posterior, gamma, steps, EM_steps, n, n_1, down, log_factorial_Y) {
    .Call('_scPoissonGamma_EM_PoissonGamma_alt', PACKAGE = 'scPoissonGamma', Y, X, Y_ind_zero, psi, mu1, mu2, posterior, gamma, steps, EM_steps, n, n_1, down, log_factorial_Y)
}

PoissonGamma_Mix <- function(Y, X, psi, gamma, steps, EM_steps, down, LRT, group, ReportAll) {
    .Call('_scPoissonGamma_PoissonGamma_Mix', PACKAGE = 'scPoissonGamma', Y, X, psi, gamma, steps, EM_steps, down, LRT, group, ReportAll)
}

gradient_multiple_beta_all <- function(Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k) {
    .Call('_scPoissonGamma_gradient_multiple_beta_all', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k)
}

gradient_multiple_beta_all_cov <- function(Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k) {
    .Call('_scPoissonGamma_gradient_multiple_beta_all_cov', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k)
}

Expected_logLikelihood_multiple_beta <- function(Y, X, Z, Xbeta, psi, delta, mu1, mu2, alphaXbeta, posterior, n, log_factorial_Y) {
    .Call('_scPoissonGamma_Expected_logLikelihood_multiple_beta', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, psi, delta, mu1, mu2, alphaXbeta, posterior, n, log_factorial_Y)
}

LogLikelihood_single_multiple_beta <- function(Y_i, Xbeta_i, psi, mu2, log_factorial_Y_i) {
    .Call('_scPoissonGamma_LogLikelihood_single_multiple_beta', PACKAGE = 'scPoissonGamma', Y_i, Xbeta_i, psi, mu2, log_factorial_Y_i)
}

Posterior_prob_multiple_beta <- function(Y_i, Xbeta_i, Z_i, psi, delta, mu1, mu2, alphaXbeta_i, log_factorial_Y_i) {
    .Call('_scPoissonGamma_Posterior_prob_multiple_beta', PACKAGE = 'scPoissonGamma', Y_i, Xbeta_i, Z_i, psi, delta, mu1, mu2, alphaXbeta_i, log_factorial_Y_i)
}

PoissonMix_stepsize_for_mutiple_beta <- function(Y, X, Z, Xbeta, alphaXbeta, betas, ind, m_gra_beta, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_mutiple_beta', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, betas, ind, m_gra_beta, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_mutiple_beta_for_psi <- function(Y, X, Z, Xbeta, alphaXbeta, gra_psi, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_mutiple_beta_for_psi', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, gra_psi, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_mutiple_beta_for_mu1 <- function(Y, X, Z, Xbeta, alphaXbeta, gra_mu1, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_mutiple_beta_for_mu1', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, gra_mu1, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_mutiple_beta_for_mu2 <- function(Y, X, Z, Xbeta, alphaXbeta, gra_mu2, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_mutiple_beta_for_mu2', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, gra_mu2, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_mutiple_beta_for_delta <- function(Y, X, Z, Xbeta, alphaXbeta, gra_delta, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_mutiple_beta_for_delta', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, gra_delta, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y)
}

PoissonMix_stepsize_for_mutiple_alpha <- function(Y, X, Z, Xbeta, Xbeta_mat, alphaXbeta, alphas, ind, m_gra_alpha, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_mutiple_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, Xbeta_mat, alphaXbeta, alphas, ind, m_gra_alpha, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y)
}

gradient_descent_PoissonGamma_mutiple_beta <- function(Y, X, Z, Xbeta, alphaXbeta, betas, psi, delta, mu1, mu2, alphas, posterior, n, k, gamma, steps, down, log_factorial_Y) {
    .Call('_scPoissonGamma_gradient_descent_PoissonGamma_mutiple_beta', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, betas, psi, delta, mu1, mu2, alphas, posterior, n, k, gamma, steps, down, log_factorial_Y)
}

Fisher_information_multiple_beta <- function(Y, X, Z, Xbeta, alphaXbeta, betas, alphas, psi, delta, mu1, mu2, posterior, n, k) {
    .Call('_scPoissonGamma_Fisher_information_multiple_beta', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, betas, alphas, psi, delta, mu1, mu2, posterior, n, k)
}

EM_PoissonGamma_multiple_beta <- function(Y, X, Z, Y_ind_zero, betas, psi, mu1, mu2, delta, alphas, posterior, gamma, steps, EM_steps, n, k, n_1, down, log_factorial_Y, ReportAll) {
    .Call('_scPoissonGamma_EM_PoissonGamma_multiple_beta', PACKAGE = 'scPoissonGamma', Y, X, Z, Y_ind_zero, betas, psi, mu1, mu2, delta, alphas, posterior, gamma, steps, EM_steps, n, k, n_1, down, log_factorial_Y, ReportAll)
}

PoissonGamma_Mix_multiple_beta <- function(Y, X, Z, psi, gamma, steps, EM_steps, down, group, ReportAll) {
    .Call('_scPoissonGamma_PoissonGamma_Mix_multiple_beta', PACKAGE = 'scPoissonGamma', Y, X, Z, psi, gamma, steps, EM_steps, down, group, ReportAll)
}

PoissonMix_stepsize_for_mutiple_alpha_nowith_alpha <- function(Y, X, Z, Xbeta, alphaXbeta, alphas, ind, m_gra_alpha, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y) {
    .Call('_scPoissonGamma_PoissonMix_stepsize_for_mutiple_alpha_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, alphas, ind, m_gra_alpha, ll, psi, delta, mu1, mu2, posterior, n, gamma, down, log_factorial_Y)
}

gradient_multiple_beta_all_nowith_alpha <- function(Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k) {
    .Call('_scPoissonGamma_gradient_multiple_beta_all_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k)
}

gradient_multiple_beta_all_cov_nowith_alpha <- function(Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k) {
    .Call('_scPoissonGamma_gradient_multiple_beta_all_cov_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, beta, psi, delta, mu1, mu2, alpha, posterior, n, k)
}

gradient_descent_PoissonGamma_mutiple_beta_nowith_alpha <- function(Y, X, Z, Xbeta, alphaXbeta, betas, psi, delta, mu1, mu2, alphas, posterior, n, k, gamma, steps, down, log_factorial_Y) {
    .Call('_scPoissonGamma_gradient_descent_PoissonGamma_mutiple_beta_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, betas, psi, delta, mu1, mu2, alphas, posterior, n, k, gamma, steps, down, log_factorial_Y)
}

Fisher_information_multiple_beta_nowith_alpha <- function(Y, X, Z, Xbeta, alphaXbeta, betas, alphas, psi, delta, mu1, mu2, posterior, n, k) {
    .Call('_scPoissonGamma_Fisher_information_multiple_beta_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, Xbeta, alphaXbeta, betas, alphas, psi, delta, mu1, mu2, posterior, n, k)
}

EM_PoissonGamma_multiple_beta_nowith_alpha <- function(Y, X, Z, Y_ind_zero, betas, psi, mu1, mu2, delta, alphas, posterior, gamma, steps, EM_steps, n, k, n_1, down, log_factorial_Y, ReportAll) {
    .Call('_scPoissonGamma_EM_PoissonGamma_multiple_beta_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, Y_ind_zero, betas, psi, mu1, mu2, delta, alphas, posterior, gamma, steps, EM_steps, n, k, n_1, down, log_factorial_Y, ReportAll)
}

PoissonGamma_Mix_multiple_beta_nowith_alpha <- function(Y, X, Z, psi, gamma, steps, EM_steps, down, group, ReportAll) {
    .Call('_scPoissonGamma_PoissonGamma_Mix_multiple_beta_nowith_alpha', PACKAGE = 'scPoissonGamma', Y, X, Z, psi, gamma, steps, EM_steps, down, group, ReportAll)
}

Mix_gradient_and_LogLikelihood_for_individual_sample <- function(Y, W, V, WY, WWY, W3Y, W4Y, VY, VVY, V3Y, V4Y, WW, W3, W4, VV, V3, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, psi, n, sum_log_factorial_Y) {
    .Call('_scPoissonGamma_Mix_gradient_and_LogLikelihood_for_individual_sample', PACKAGE = 'scPoissonGamma', Y, W, V, WY, WWY, W3Y, W4Y, VY, VVY, V3Y, V4Y, WW, W3, W4, VV, V3, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, psi, n, sum_log_factorial_Y)
}

Mix_LogLikelihood_for_individual_sample <- function(Y, W, V, WW, VV, W3, V3, W4, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, psi, n, sum_log_factorial_Y) {
    .Call('_scPoissonGamma_Mix_LogLikelihood_for_individual_sample', PACKAGE = 'scPoissonGamma', Y, W, V, WW, VV, W3, V3, W4, V4, a0, a1, a2, a3, a4, b1, b2, b3, b4, psi, n, sum_log_factorial_Y)
}

Mix_select_stepsize_for_a_parameter <- function(Y, W, V, WW, VV, W3, V3, W4, V4, ll, sum_log_factorial_Y, gradient, parameters, ind, gamma, n, down) {
    .Call('_scPoissonGamma_Mix_select_stepsize_for_a_parameter', PACKAGE = 'scPoissonGamma', Y, W, V, WW, VV, W3, V3, W4, V4, ll, sum_log_factorial_Y, gradient, parameters, ind, gamma, n, down)
}

Mix_gradient_descent_for_individual_sample <- function(Y, W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4, psi, gamma, steps, down) {
    .Call('_scPoissonGamma_Mix_gradient_descent_for_individual_sample', PACKAGE = 'scPoissonGamma', Y, W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4, psi, gamma, steps, down)
}

Predict_for_individual_sample <- function(W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4) {
    .Call('_scPoissonGamma_Predict_for_individual_sample', PACKAGE = 'scPoissonGamma', W, V, a0, a1, a2, a3, a4, b1, b2, b3, b4)
}

reweighting_sum_C <- function(Ymat, Yflagmat, Y, Yflag, prior_weight, ImputeAll) {
    .Call('_scPoissonGamma_reweighting_sum_C', PACKAGE = 'scPoissonGamma', Ymat, Yflagmat, Y, Yflag, prior_weight, ImputeAll)
}

reweighting_C <- function(Ymat, Yflagmat, Y, Yflag) {
    .Call('_scPoissonGamma_reweighting_C', PACKAGE = 'scPoissonGamma', Ymat, Yflagmat, Y, Yflag)
}

